# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.10@sha256:f66273e014b307e4ac46778845ebc1e9ee24b2e57c1fc17d5ec5ac3015649bfa
    ports:
      - "8096:8096"
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - jellyfin-media:/media
    environment:
      - JELLYFIN_PublishedServerUrl=http://localhost:8096
    restart: unless-stopped

volumes:
  jellyfin-config:
  jellyfin-cache:
  jellyfin-media:
