// Copyright IBM Corp. 2021, 2025
// SPDX-License-Identifier: MPL-2.0

package main

// The JSON names below are the ones each resource's Read looks up, so the
// generated configuration sets exactly the attributes the imported state
// holds.

var systemFields = []hclField{
	{json: "EnableMetrics", attr: "enable_metrics"},
	// Jellyfin sends EnableNormalizedItemByNameIds and
	// EnableCaseSensitiveItemIds, which the Read's IDs spelling does not
	// match, so the imported state holds null for both and they must stay
	// out of the configuration.
	{json: "EnableNormalizedItemByNameIDs", attr: "enable_normalized_item_by_name_ids"},
	{json: "IsPortAuthorized", attr: "is_port_authorized"},
	{json: "QuickConnectAvailable", attr: "quick_connect_available"},
	{json: "EnableCaseSensitiveItemIDs", attr: "enable_case_sensitive_item_ids"},
	{json: "DisableLiveTvChannelUserDataName", attr: "disable_live_tv_channel_user_data_name"},
	{json: "MetadataPath", attr: "metadata_path"},
	{json: "PreferredMetadataLanguage", attr: "preferred_metadata_language"},
	{json: "MetadataCountryCode", attr: "metadata_country_code"},
	{json: "SortReplaceCharacters", attr: "sort_replace_characters"},
	{json: "SortRemoveCharacters", attr: "sort_remove_characters"},
	{json: "SortRemoveWords", attr: "sort_remove_words"},
	{json: "MinResumePct", attr: "min_resume_pct"},
	{json: "MaxResumePct", attr: "max_resume_pct"},
	{json: "MinResumeDurationSeconds", attr: "min_resume_duration_seconds"},
	{json: "MinAudiobookResume", attr: "min_audiobook_resume"},
	{json: "MaxAudiobookResume", attr: "max_audiobook_resume"},
	{json: "InactiveSessionThreshold", attr: "inactive_session_threshold"},
	{json: "LibraryMonitorDelay", attr: "library_monitor_delay"},
	{json: "LibraryUpdateDuration", attr: "library_update_duration"},
	{json: "CacheSize", attr: "cache_size"},
	{json: "ImageSavingConvention", attr: "image_saving_convention"},
	{json: "MetadataOptions", attr: "metadata_options", nested: []hclField{
		{json: "ItemType", attr: "item_type"},
		{json: "DisabledMetadataSavers", attr: "disabled_metadata_savers"},
		{json: "LocalMetadataReaderOrder", attr: "local_metadata_reader_order"},
		{json: "DisabledMetadataFetchers", attr: "disabled_metadata_fetchers"},
		{json: "MetadataFetcherOrder", attr: "metadata_fetcher_order"},
		{json: "DisabledImageFetchers", attr: "disabled_image_fetchers"},
		{json: "ImageFetcherOrder", attr: "image_fetcher_order"},
	}},
	{json: "SkipDeserializationForBasicTypes", attr: "skip_deserialization_for_basic_types"},
	{json: "UICulture", attr: "ui_culture"},
	{json: "SaveMetadataHidden", attr: "save_metadata_hidden"},
	{json: "ContentTypes", attr: "content_types", nested: []hclField{
		{json: "Name", attr: "name"},
		{json: "Value", attr: "value"},
	}},
	{json: "RemoteClientBitrateLimit", attr: "remote_client_bitrate_limit"},
	{json: "EnableFolderView", attr: "enable_folder_view"},
	{json: "EnableGroupingMoviesIntoCollections", attr: "enable_grouping_movies_into_collections"},
	{json: "EnableGroupingShowsIntoCollections", attr: "enable_grouping_shows_into_collections"},
	{json: "DisplaySpecialsWithinSeasons", attr: "display_specials_within_seasons"},
	{json: "CodecsUsed", attr: "codecs_used"},
	{json: "EnableExternalContentInSuggestions", attr: "enable_external_content_in_suggestions"},
	{json: "ImageExtractionTimeoutMs", attr: "image_extraction_timeout_ms"},
	{json: "PathSubstitutions", attr: "path_substitutions", nested: []hclField{
		{json: "From", attr: "from"},
		{json: "To", attr: "to"},
	}},
	{json: "EnableSlowResponseWarning", attr: "enable_slow_response_warning"},
	{json: "SlowResponseThresholdMs", attr: "slow_response_threshold_ms"},
	{json: "CorsHosts", attr: "cors_hosts"},
	{json: "ActivityLogRetentionDays", attr: "activity_log_retention_days"},
	{json: "LibraryScanFanoutConcurrency", attr: "library_scan_fanout_concurrency"},
	{json: "LibraryMetadataRefreshConcurrency", attr: "library_metadata_refresh_concurrency"},
	{json: "AllowClientLogUpload", attr: "allow_client_log_upload"},
	{json: "DummyChapterDuration", attr: "dummy_chapter_duration"},
	{json: "ChapterImageResolution", attr: "chapter_image_resolution"},
	{json: "ParallelImageEncodingLimit", attr: "parallel_image_encoding_limit"},
	{json: "CastReceiverApplications", attr: "cast_receiver_applications", nested: []hclField{
		{json: "Id", attr: "id"},
		{json: "Name", attr: "name"},
	}},
	{json: "TrickplayOptions", attr: "trickplay_options", object: true, nested: []hclField{
		{json: "EnableHwAcceleration", attr: "enable_hw_acceleration"},
		{json: "EnableHwEncoding", attr: "enable_hw_encoding"},
		{json: "EnableKeyFrameOnlyExtraction", attr: "enable_key_frame_only_extraction"},
		{json: "ScanBehavior", attr: "scan_behavior"},
		// Jellyfin sends ProcessPriority, so this stays out for the same
		// reason as the ...IDs fields above.
		{json: "ProcessPriorityClass", attr: "process_priority"},
		{json: "Interval", attr: "interval"},
		{json: "WidthResolutions", attr: "width_resolutions"},
		{json: "TileWidth", attr: "tile_width"},
		{json: "TileHeight", attr: "tile_height"},
		{json: "Qscale", attr: "qscale"},
		{json: "JpegQuality", attr: "jpeg_quality"},
		{json: "ProcessThreads", attr: "process_threads"},
	}},
	{json: "EnableLegacyAuthorization", attr: "enable_legacy_authorization"},
	{json: "LogFileRetentionDays", attr: "log_file_retention_days"},
	{json: "CachePath", attr: "cache_path"},
	{json: "ServerName", attr: "server_name"},
}

var encodingFields = []hclField{
	{json: "EncodingThreadCount", attr: "encoding_thread_count"},
	{json: "TranscodingTempPath", attr: "transcoding_temp_path"},
	{json: "FallbackFontPath", attr: "fallback_font_path"},
	{json: "EnableFallbackFont", attr: "enable_fallback_font"},
	{json: "EnableAudioVbr", attr: "enable_audio_vbr"},
	{json: "DownMixAudioBoost", attr: "down_mix_audio_boost"},
	{json: "DownMixStereoAlgorithm", attr: "down_mix_stereo_algorithm"},
	{json: "MaxMuxingQueueSize", attr: "max_muxing_queue_size"},
	{json: "EnableThrottling", attr: "enable_throttling"},
	{json: "ThrottleDelaySeconds", attr: "throttle_delay_seconds"},
	{json: "EnableSegmentDeletion", attr: "enable_segment_deletion"},
	{json: "SegmentKeepSeconds", attr: "segment_keep_seconds"},
	{json: "HardwareAccelerationType", attr: "hardware_acceleration_type"},
	{json: "EncoderAppPath", attr: "encoder_app_path"},
	{json: "EncoderAppPathDisplay", attr: "encoder_app_path_display"},
	{json: "VaapiDevice", attr: "vaapi_device"},
	{json: "QsvDevice", attr: "qsv_device"},
	{json: "EnableTonemapping", attr: "enable_tonemapping"},
	{json: "EnableVppTonemapping", attr: "enable_vpp_tonemapping"},
	{json: "EnableVideoToolboxTonemapping", attr: "enable_video_toolbox_tonemapping"},
	{json: "TonemappingAlgorithm", attr: "tonemapping_algorithm"},
	{json: "TonemappingMode", attr: "tonemapping_mode"},
	{json: "TonemappingRange", attr: "tonemapping_range"},
	{json: "TonemappingDesat", attr: "tonemapping_desat"},
	{json: "TonemappingPeak", attr: "tonemapping_peak"},
	{json: "TonemappingParam", attr: "tonemapping_param"},
	{json: "VppTonemappingBrightness", attr: "vpp_tonemapping_brightness"},
	{json: "VppTonemappingContrast", attr: "vpp_tonemapping_contrast"},
	{json: "H264Crf", attr: "h264_crf"},
	{json: "H265Crf", attr: "h265_crf"},
	{json: "EncoderPreset", attr: "encoder_preset"},
	{json: "DeinterlaceDoubleRate", attr: "deinterlace_double_rate"},
	{json: "DeinterlaceMethod", attr: "deinterlace_method"},
	{json: "EnableDecodingColorDepth10Hevc", attr: "enable_decoding_color_depth10_hevc"},
	{json: "EnableDecodingColorDepth10Vp9", attr: "enable_decoding_color_depth10_vp9"},
	{json: "EnableDecodingColorDepth10HevcRext", attr: "enable_decoding_color_depth10_hevc_rext"},
	{json: "EnableDecodingColorDepth12HevcRext", attr: "enable_decoding_color_depth12_hevc_rext"},
	{json: "EnableEnhancedNvdecDecoder", attr: "enable_enhanced_nvdec_decoder"},
	{json: "PreferSystemNativeHwDecoder", attr: "prefer_system_native_hw_decoder"},
	{json: "EnableIntelLowPowerH264HwEncoder", attr: "enable_intel_low_power_h264_hw_encoder"},
	{json: "EnableIntelLowPowerHevcHwEncoder", attr: "enable_intel_low_power_hevc_hw_encoder"},
	{json: "EnableHardwareEncoding", attr: "enable_hardware_encoding"},
	{json: "AllowHevcEncoding", attr: "allow_hevc_encoding"},
	{json: "AllowAv1Encoding", attr: "allow_av1_encoding"},
	{json: "EnableSubtitleExtraction", attr: "enable_subtitle_extraction"},
	{json: "SubtitleExtractionTimeoutMinutes", attr: "subtitle_extraction_timeout_minutes"},
	{json: "HardwareDecodingCodecs", attr: "hardware_decoding_codecs"},
	{json: "AllowOnDemandMetadataBasedKeyframeExtractionForExtensions", attr: "allow_on_demand_metadata_based_keyframe_extraction_for_extensions"},
	{json: "HlsAudioSeekStrategy", attr: "hls_audio_seek_strategy"},
}

// certificate_password is left out so the generated file holds no secret;
// the imported state keeps it because the attribute is optional and computed.
var networkingFields = []hclField{
	{json: "BaseUrl", attr: "base_url"},
	{json: "EnableHttps", attr: "enable_https"},
	{json: "RequireHttps", attr: "require_https"},
	{json: "CertificatePath", attr: "certificate_path"},
	{json: "InternalHttpPort", attr: "internal_http_port"},
	{json: "InternalHttpsPort", attr: "internal_https_port"},
	{json: "PublicHttpPort", attr: "public_http_port"},
	{json: "PublicHttpsPort", attr: "public_https_port"},
	{json: "AutoDiscovery", attr: "auto_discovery"},
	{json: "EnableUPnP", attr: "enable_upnp"},
	{json: "EnableIPv4", attr: "enable_ipv4"},
	{json: "EnableIPv6", attr: "enable_ipv6"},
	{json: "EnableRemoteAccess", attr: "enable_remote_access"},
	{json: "LocalNetworkSubnets", attr: "local_network_subnets"},
	{json: "LocalNetworkAddresses", attr: "local_network_addresses"},
	{json: "KnownProxies", attr: "known_proxies"},
	{json: "IgnoreVirtualInterfaces", attr: "ignore_virtual_interfaces"},
	{json: "VirtualInterfaceNames", attr: "virtual_interface_names"},
	{json: "EnablePublishedServerUriByRequest", attr: "enable_published_server_uri_by_request"},
	{json: "PublishedServerUriBySubnet", attr: "published_server_uri_by_subnet"},
	{json: "RemoteIPFilter", attr: "remote_ip_filter"},
	{json: "IsRemoteIPFilterBlacklist", attr: "is_remote_ip_filter_blacklist"},
}

var brandingFields = []hclField{
	{json: "LoginDisclaimer", attr: "login_disclaimer"},
	{json: "CustomCss", attr: "custom_css"},
	{json: "SplashscreenEnabled", attr: "splashscreen_enabled"},
	{json: "SplashscreenLocation", attr: "splashscreen_location"},
}

var metadataFields = []hclField{
	{json: "UseFileCreationTimeForDateAdded", attr: "use_file_creation_time_for_date_added"},
}
